---
version: "3.9"

services:
  steam-headless:
    image: josh5/steam-headless:latest
    restart: unless-stopped
    shm_size: ${SHM_SIZE:-2G}
    ipc: host
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              device_ids: ["${NVIDIA_VISIBLE_DEVICES:-all}"]
    network_mode: host
    hostname: ${NAME:-SteamHeadless}
    extra_hosts:
      - "${NAME:-SteamHeadless}:127.0.0.1"
    environment:
      - TZ=${TZ:-Etc/UTC}
      - USER_LOCALES=${USER_LOCALES:-en_US.UTF-8 UTF-8}
      - DISPLAY=${DISPLAY:-:55}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - UMASK=${UMASK:-000}
      - USER_PASSWORD=${USER_PASSWORD?Variable USER_PASSWORD not set}
      - MODE=${MODE:-primary}
      - WEB_UI_MODE=${WEB_UI_MODE:-vnc}
      - ENABLE_VNC_AUDIO=${ENABLE_VNC_AUDIO:-true}
      - PORT_NOVNC_WEB=${PORT_NOVNC_WEB:-58083}
      - NEKO_NAT1TO1=${NEKO_NAT1TO1}
      - ENABLE_STEAM=${ENABLE_STEAM:-true}
      - STEAM_ARGS=${STEAM_ARGS:-"-silent"}
      - ENABLE_SUNSHINE=${ENABLE_SUNSHINE:-false}
      - SUNSHINE_USER=${SUNSHINE_USER:-admin}
      - SUNSHINE_PASS=${SUNSHINE_PASS:-admin}
      - ENABLE_EVDEV_INPUTS=${ENABLE_EVDEV_INPUTS:-true}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-all}
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
      - NVIDIA_DRIVER_VERSION=${NVIDIA_DRIVER_VERSION}
    devices:
      - /dev/fuse
      - /dev/uinput
      # Add AMD/Intel HW accelerated video encoding/decoding devices [OPTIONAL].
      #- /dev/dri
      # Add NVIDIA HW accelerated devices [OPTIONAL - If you use the nvidia container toolkit, this is not needed].
      #- /dev/nvidia0
      #- /dev/nvidiactl
      #- /dev/nvidia-modeset
      #- /dev/nvidia-uvm
      #- /dev/nvidia-uvm-tools
      #- /dev/nvidia-caps/nvidia-cap1
      #- /dev/nvidia-caps/nvidia-cap2
    device_cgroup_rules:
      - 'c 13:* rmw'
    volumes:
      - ${HOME_DIR}/:/home/default/:rw
      - ${GAMES_DIR}/:/mnt/games/:rw
